---
title: "psychosis analysis"
output:
  html_document: default
  pdf_document: default
date: "2024-02-20"
---

# package import

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```

# data import + lexical

```{r}
final_subjects = readxl::read_excel("final_subjects_for_AK_analysis.xlsx") %>%
  pull(subject)

v1data = read_csv("forager_results/output/lexical_results.csv") %>% 
  mutate(version = "V1") %>%
  filter(Subject %in% final_subjects)

write.csv(v1data, "results/subject_lexical_results.csv", row.names = FALSE)
write.csv(v1data, "simdrop_inclusive/subject_lexical_results.csv", row.names = FALSE)

```


# best model

## individual best models

```{r}

v1models = read_csv("forager_results/output/model_results.csv") %>%
  mutate(version = "V1")%>%
  filter(Subject %in% final_subjects)



# confirm no missing nLLs
which(is.na(v1models$Negative_Log_Likelihood_Optimized))

parameter_file = read_csv("parameters.csv")
subject_scores = read_csv("forager_results/output/individual_descriptive_stats.csv") %>%
  rename(n = `#_of_Items`) %>%
  select(Subject, n) %>% filter(!is.na(n)) %>%
  filter(Subject %in% final_subjects)

subjectBICs = v1models %>% 
  left_join(parameter_file) %>% left_join(subject_scores)%>%
  group_by(Subject) %>%
  mutate(BIC = k * log(n) - 2 * (-Negative_Log_Likelihood_Optimized))
  

## only include troyer, delta, and multimodal delta
subject_best_model_stats =subjectBICs %>% 
  filter(str_detect(Model, "multimodaldelta|troyerextended\\b")) %>%
  group_by(Subject) %>%
  slice_min(BIC)

write.csv(subject_best_model_stats, 
          "results/individual_best_models.csv", row.names = FALSE)
```
### simdrop included best models
```{r}
subject_best_model_stats_overall =subjectBICs %>% 
  group_by(Subject) %>%
  slice_min(BIC)

write.csv(subject_best_model_stats_overall, 
          "simdrop_inclusive/individual_best_models.csv", row.names = FALSE)
```

## best overall models
```{r}
randomBICs = subjectBICs %>%
  filter(Model == "forage_random_baseline") %>%
  select(Subject, BIC) %>%
  rename(randomBIC = BIC)

modelBICs = subjectBICs %>% 
  left_join(randomBICs)%>%
  mutate(deltaBIC = randomBIC - BIC) #%>%
  group_by(Subject, Model) %>%
  summarise(meanBIC = mean(deltaBIC)) 

## best model for each subject = largest improvement from random model
best_model_subject = modelBICs %>% 
  filter(str_detect(Model, "multimodaldelta|troyerextended|forage_random_baseline|forage_static")) %>%
  group_by(Subject) %>% 
  slice_max(deltaBIC)

best_model_name = modelBICs %>%
  filter(str_detect(Model, "multimodaldelta|\\bdelta\\b|forage_random_baseline")) %>%
  arrange(desc(meanBIC)) %>%
  slice(1) %>% 
  ungroup() %>%
  pull(Model)

best_model_name

# norm_based LLs
best_betas = subjectBICs %>% 
  filter(str_detect(Model, "phonologicaldynamiclocal_troyerextended") |
           str_detect(Model, best_model_name))

write.csv(best_betas, "results/subject_salience_values.csv", row.names = FALSE)

best_betas_overall = best_betas %>%
  pivot_longer(names_to = "parameter", cols=Beta_Frequency:Beta_Phonological) %>%
  group_by(version, Model, parameter) %>%
  summarize(mean_value = mean(value))  %>%
  pivot_wider(names_from = parameter, values_from = mean_value)

write.csv(best_betas_overall, "results/overall_salience_values.csv", row.names = FALSE)
```

### simdrop

```{r}
overall_best_model_name = modelBICs %>%
  arrange(desc(meanBIC)) %>%
  slice(1) %>% 
  ungroup() %>%
  pull(Model)

overall_best_model_name

# norm_based LLs
simdrop_best_betas = subjectBICs %>% 
  filter(str_detect(Model, "phonologicaldynamiclocal_troyerextended") |
           str_detect(Model, overall_best_model_name)|
         str_detect(Model, best_model_name))

write.csv(best_betas, "simdrop_inclusive/subject_salience_values.csv", row.names = FALSE)

simdrop_best_betas_overall = simdrop_best_betas %>%
  pivot_longer(names_to = "parameter", cols=Beta_Frequency:Beta_Phonological) %>%
  group_by(version, Model, parameter) %>%
  summarize(mean_value = mean(value))  %>%
  pivot_wider(names_from = parameter, values_from = mean_value)

write.csv(simdrop_best_betas_overall, "simdrop_inclusive/overall_salience_values.csv", row.names = FALSE)

```


# switch results

```{r}
Switch_Methods = c("troyerextended", "multimodaldelta_alpha=1.0_rise=0.25_fall=1.0")
switchv1data = read_csv("forager_results/output/switch_results.csv") %>% 
  filter(Switch_Method %in% Switch_Methods)%>%
  filter(Subject %in% final_subjects) 

write.csv(switchv1data, "results/subject_switch_results.csv", row.names = FALSE)
```
## simdrop inclusive results
```{r}
simdrop_switchv1data = read_csv("forager_results/output/switch_results.csv") %>% 
  filter(Switch_Method %in% c(Switch_Methods, "simdrop"))%>%
  filter(Subject %in% final_subjects) 

write.csv(switchv1data, "simdrop_inclusive/subject_switch_results.csv", row.names = FALSE)
```

## best-subject-switch

```{r}
best_subject_switch = subject_best_model_stats %>% 
  separate(Model, sep = "_", into = c("forage", "model", "switch_method", "p1", "p2", "p3")) %>%
  mutate(
    switch_method = if_else(
      is.na(p1) | is.na(p2) | is.na(p3),
      switch_method,
      str_c(switch_method, p1, p2, p3, sep = "_")
    )
  ) %>%
  select(-p1, -p2, -p3)  

best_subject_switchv1data = read_csv("forager_results/output/switch_results.csv") %>%
  filter(Subject %in% final_subjects) %>%
   inner_join(
    best_subject_switch %>% select(Subject, switch_method),
    by = c("Subject", "Switch_Method" = "switch_method")
  )

write.csv(best_subject_switchv1data, "results/best_subject_switch.csv", row.names = FALSE)
```


## compare 

```{r}
s = read_csv("results/subject_switch_results.csv") %>%
  group_by(Subject, Switch_Method) %>%
  mutate(item = row_number()) %>% ungroup() %>%
  pivot_wider(names_from = Switch_Method, values_from = Switch_Value)

l = read_csv("results/subject_lexical_results.csv") %>%
  group_by(Subject) %>%
  mutate(item = row_number()) %>% ungroup() %>%
  left_join(s) %>%
  rename(delta = "multimodaldelta_alpha=1.0_rise=0.25_fall=1.0")%>%
  select(Subject, Fluency_Item, Semantic_Similarity, item, delta, troyerextended) %>%
  mutate(mismatch = ifelse(delta != troyerextended, 1,0))
```

## individual results
```{r}
individual_stats = read_csv("forager_results/output/individual_descriptive_stats.csv") %>%
  filter(Switch_Method %in% Switch_Methods) %>%
  select(Subject, Switch_Method:Cluster_Size_std)%>%
  filter(Subject %in% final_subjects)

write.csv(individual_stats, "results/subject_individual_stats.csv", row.names = FALSE)


### best subject 

best_subject_individual_stats = read_csv("forager_results/output/individual_descriptive_stats.csv") %>%
  filter(Subject %in% final_subjects) %>%
   inner_join(
    best_subject_switch %>% select(Subject, switch_method),
    by = c("Subject", "Switch_Method" = "switch_method")
  ) %>%
  select(Subject, Switch_Method:Cluster_Size_std)

write.csv(best_subject_individual_stats, 
          "results/subject_best_models/best_subject_individual_stats.csv", 
          row.names = FALSE)
```
### simdrop inclusive results
```{r}
individual_stats = read_csv("forager_results/output/individual_descriptive_stats.csv") %>%
  filter(Switch_Method %in% c(Switch_Methods, "simdrop")) %>%
  select(Subject, Switch_Method:Cluster_Size_std)%>%
  filter(Subject %in% final_subjects)

write.csv(individual_stats, "simdrop_inclusive/subject_individual_stats.csv", row.names = FALSE)
```

# checking
```{r}
matlab = read.delim("MATLAB_summary_results.txt", sep = "\t")
forager = read_csv("forager_results/output/individual_descriptive_stats.csv") 
# troyer
switch_metrics = forager %>% filter(Switch_Method == "troyerextended") %>%
  select(Subject,Switch_Method:Cluster_Size_std)

# delta

switch_metrics = forager %>% filter(Switch_Method == "delta_rise=0.0_fall=1.0") %>%
  select(Subject,Switch_Method:Cluster_Size_std)

all_metrics = forager %>% filter(!is.na(Semantic_Similarity_mean)) %>%
  select(Subject: `#_of_Items`) %>% left_join(switch_metrics)

stopifnot(round(all_metrics$Semantic_Similarity_mean,2) == round(matlab$mean_overall_semantic_sim,2))
stopifnot(round(all_metrics$`#_of_Items`,2) == round(matlab$total_responses,2 ))
## troyer
stopifnot(round(all_metrics$Number_of_Switches,2) == round(matlab$switch_count_troyerF,2 ))
stopifnot(round(all_metrics$Cluster_Size_mean,2) == round(matlab$mean_cluster_size_with_singletons_troyerF,2 ))

## delta

stopifnot(round(all_metrics$Number_of_Switches,2) == round(matlab$switch_count_delta,2 ))
stopifnot(round(all_metrics$Cluster_Size_mean,2) == round(matlab$mean_cluster_size_with_singletons_delta,2 ))



```

# snafu vs. troyerextended

```{r}
switchv1data = read_csv("forager_results/output/switch_results.csv") %>% 
  mutate(v = "V1")
# switchv2data = read_csv("forager/output/corrected_V2_results/switch_results.csv") %>% 
#   mutate(v = "V2")

combinedswitch = switchv1data #rbind(switchv1data, switchv2data) 

## check if multimodal alpha = 1 is identical to delta 

switchv1data %>% filter(Switch_Method %in% c("delta_rise=0.0_fall=1.0",
                                               "multimodaldelta_alpha=1.0_rise=0.0_fall=1.0")) %>%
  group_by(Subject, Switch_Method) %>% mutate(item = row_number()) %>%
  pivot_wider(names_from = Switch_Method, values_from = Switch_Value) %>%
  mutate(eq = `delta_rise=0.0_fall=1.0` == `multimodaldelta_alpha=1.0_rise=0.0_fall=1.0`) %>%
  filter(!eq)

merged_norms = switchv1data %>% #rbind(switchv1data, switchv2data) %>% 
  filter(Switch_Method %in% c("norms_associative", "troyerextended")) %>% 
  group_by(Subject, Switch_Method) %>%
  mutate(response_number = row_number())%>%
  pivot_wider(names_from = Switch_Method, values_from = Switch_Value) %>%
  mutate(switch_match = ifelse(norms_associative == troyerextended, 1,0)) %>%
  filter(norms_associative != 2) %>% filter(troyerextended !=2)
  
# Calculate phi coefficient

final_data = merged_norms %>% filter(v == "V1")

contingency_table = table(final_data$norms_associative, final_data$troyerextended)

phi_coefficient <- psych::phi(contingency_table, digits = 5)
print(phi_coefficient)
chisq.test(contingency_table)

## organized

# Assuming your data is in merged_norms dataframe
phi_results <- merged_norms %>%
  group_by(v) %>%
  summarise(
    contingency_table = list(table(norms_associative, troyerextended)),
    phi_coefficient = list(psych::phi(table(norms_associative, troyerextended), 
                                      digits = 5)),
    chi_square_test = list(chisq.test(table(norms_associative, troyerextended)))
  )


# Print or further manipulate phi_dataframe as needed
phi_results
```

# basic lexical estimates

```{r}
lexical_mean = combinedlexical %>% 
  group_by(version, Subject) %>%
  mutate(itemno = row_number()) %>%
  filter(itemno != 1) %>%
  summarise(semantic = mean(Semantic_Similarity),
            frequency = mean(Frequency_Value),
            phon = mean(Phonological_Similarity)) %>%
  pivot_longer(names_to = "cue", cols = semantic:phon)

lexical_mean %>% 
  filter(cue == "phon")%>%
  ggplot(aes(x = version, y = value, 
             group = Subject, color = Subject)) +
  geom_point()+
  geom_line()+
  theme_clean()
```

# percent model fit

```{r}
library(dplyr)
library(ggplot2)

# Prepare switch method data
switch_counts <- best_subject_switch %>% 
  mutate(switch_method_label = 
           ifelse(switch_method == "troyerextended", "troyer", "multimodal_delta")) %>%
  group_by(switch_method_label) %>%
  count() %>% ungroup() %>%
  mutate(
    percentage = round(100 * n / sum(n), 1),
    type = "Switch Method",
    label = switch_method_label
  ) %>%
  select(type, label, n, percentage)

# Prepare model data
model_counts <- best_subject_switch %>% 
  mutate(model = case_when(model == "phonologicaldynamicglobal" ~ "p-global", 
                        model == "phonologicaldynamiclocal" ~ "p-local",
                        model == "phonologicaldynamicswitch" ~ "p-switch",
                        .default = "no-phonology")) %>%
  group_by(model) %>%
  count() %>% ungroup() %>%
  mutate(
    percentage = round(100 * n / sum(n), 1),
    type = "Model",
    label = model
  ) %>%
  select(type, label, n, percentage)

# Combine
combined_counts <- bind_rows(switch_counts, model_counts)



# Plot
ggplot(combined_counts, aes(x = type, y = percentage, fill = label)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_text(aes(label = paste0(label, ":", percentage, "%")),
            position = position_stack(vjust = 0.5),
            color = "white",
            size = 4) +
  labs(x = NULL, y = "Percentage", title = "Distribution of Best Models and Switch Methods") +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  theme(
    text = element_text(size = 12),
    legend.position = "none"
  )
```



<!-- # norms -->

<!-- ```{r} -->
<!-- troyerexnorms = readxl::read_excel("../evaluation_03_22_24/animals_norm_table_20240322.xlsx") %>% -->
<!--   pivot_longer(names_to = "Category", cols = africa:mythological) %>% -->
<!--   rename(Item = value) %>% arrange(Category) %>% filter(!is.na(Item)) %>% -->
<!--   mutate(Item = str_replace_all(Item, "_", " ")) -->

<!-- write.csv(troyerexnorms, file = "../forager_results/data/norms/troyer_extended_lundin_2024_03_22.csv", row.names = FALSE) -->
<!-- ``` -->


<!-- # OLD CODE -->
<!-- ## norms reorg -->

<!-- ```{r} -->
<!-- troyerexnorms = readxl::read_excel("../norm_data_03_05_24/animals_norm_table_20240304.xlsx") %>% -->
<!--   pivot_longer(names_to = "Category", cols = africa:mythological) %>% -->
<!--   rename(Item = value) %>% arrange(Category) %>% filter(!is.na(Item)) %>% -->
<!--   mutate(Item = str_replace_all(Item, "_", " ")) -->

<!-- write.csv(norms, file = "troyer_extended_lundin_2024_03_04.csv", row.names = FALSE) -->

<!-- snafunorms = read_csv("../forager/data/norms/animals_snafu_scheme_vocab.csv") -->
<!-- troyerextended = read_csv("../forager/data/norms/troyer_extended_lundin_2024_03_04.csv") -->

<!-- ``` -->

<!-- ## forager evaluation add -->

<!-- ```{r} -->
<!-- forager_eval = read_csv("../forager/output/nancy_V2_raw_forager_results/evaluation_results.csv") -->

<!-- snafu_items = snafunorms %>% pull(Item) -->
<!-- troyerex_items = troyerextended %>% pull(Item) -->

<!-- forager_eval = forager_eval %>%  -->
<!--   mutate(entryInSNAFU = ifelse(entry %in% snafu_items, 1, 0), -->
<!--          replacementInSNAFU = ifelse(replacement %in% snafu_items, 1, 0), -->
<!--          entryInTroyerEx = ifelse(entry %in% troyerex_items, 1, 0), -->
<!--          replacementInTroyerEx = ifelse(replacement %in% troyerex_items, 1, 0)) -->

<!-- write.csv(forager_eval, file = "files/forager_evaluation_V2.csv", row.names = FALSE) -->
<!-- ``` -->

<!-- ## OLD snafu vs. troyerextended -->

<!-- ```{r} -->
<!-- v1data = read_csv("V1/switch_results.csv") %>% mutate(v = "V1") -->
<!-- v2data = read_csv("V2/switch_results.csv") %>% mutate(v = "V2") -->

<!-- snafu = rbind(v1data, v2data) %>% #v1data %>%  -->
<!--   filter(Switch_Method == "norms_associative") %>% -->
<!--   select(-Switch_Method) %>% -->
<!--   rename(norms_snafu_associative = Switch_Value) %>% -->
<!--   mutate(Fluency_Item = str_replace_all(Fluency_Item, "_", "")) %>% -->
<!--   mutate(Fluency_Item = str_replace_all(Fluency_Item, " ", "")) %>% -->
<!--   filter(Fluency_Item != "mammal") -->

<!-- troyerex_v1 = read.delim("../norm_data_03_05_24/troyer_V1_AKcorrected.txt")%>%  -->
<!--   mutate(version = "V1") -->
<!-- troyerex_v2 = read.delim("../norm_data_03_05_24/troyer_V2_AKcorrected.txt")%>%  -->
<!--   mutate(version = "V2") -->

<!-- troyerex = rbind(troyerex_v1, troyerex_v2) %>% #troyerex_v1 %>% # -->
<!--   select(subject, response, troyer_fluid_switch, troyer_static_switch, version) %>% -->
<!--   mutate(response = str_replace_all(response, "_", "")) %>% -->
<!--   mutate(response = str_replace_all(response, " ", "")) -->

<!-- # write.csv(snafu, file = "snafu.csv", row.names = FALSE) -->
<!-- # write.csv(troyerex, file="troyer.csv", row.names = FALSE) -->

<!-- merged_norms = cbind(snafu, troyerex) %>%  -->
<!--   mutate(response_match = ifelse(Fluency_Item == response, 1, 0), -->
<!--          switch_match = ifelse(norms_snafu_associative == troyer_fluid_switch, 1,0)) %>% -->
<!--   filter(norms_snafu_associative != 2) %>% filter(troyer_fluid_switch !=2) -->

<!-- write.csv(merged_norms, file = "files/merged_snafu_troyerex.csv", row.names = FALSE) -->


<!-- # Calculate phi coefficient -->

<!-- final_data = merged_norms %>% filter(version == "V1") -->

<!-- contingency_table = table(final_data$norms_snafu_associative, final_data$troyer_fluid_switch) -->

<!-- phi_coefficient <- psych::phi(contingency_table, digits = 5) -->
<!-- print(phi_coefficient) -->
<!-- chisq.test(contingency_table) -->

<!-- ## organized -->

<!-- # Assuming your data is in merged_norms dataframe -->
<!-- phi_results <- merged_norms %>% -->
<!--   group_by(version) %>% -->
<!--   summarise( -->
<!--     contingency_table = list(table(norms_snafu_associative, troyer_fluid_switch)), -->
<!--     phi_coefficient = list(psych::phi(table(norms_snafu_associative, troyer_fluid_switch), digits = 5)), -->
<!--     chi_square_test = list(chisq.test(table(norms_snafu_associative, troyer_fluid_switch))) -->
<!--   ) -->


<!-- # Print or further manipulate phi_dataframe as needed -->
<!-- print(phi_results) -->
<!-- ``` -->

<!-- ## OLD troyerextended comparison -->

<!-- ```{r} -->
<!-- forager_troyerex = rbind(v1data, v2data) %>%  -->
<!--   filter(Switch_Method == "troyerextended") %>%  -->
<!--   rename(forager_troyerex = Switch_Value) %>% -->
<!--   select(-Switch_Method) %>% -->
<!--   mutate(Fluency_Item = str_replace_all(Fluency_Item, "_", "")) %>% -->
<!--   mutate(Fluency_Item = str_replace_all(Fluency_Item, " ", "")) %>% -->
<!--   filter(Fluency_Item != "mammal") -->

<!-- troyerex = rbind(troyerex_v1, troyerex_v2) %>%  -->
<!--   select(subject, response, troyer_fluid_switch, troyer_static_switch, version) %>% -->
<!--   mutate(response = str_replace_all(response, "_", "")) %>% -->
<!--   mutate(response = str_replace_all(response, " ", "")) -->

<!-- troyerex_compare = cbind(forager_troyerex, troyerex) %>% -->
<!--   mutate(response_match = ifelse(Fluency_Item == response, 1, 0), -->
<!--          switch_match = ifelse(forager_troyerex == troyer_fluid_switch, 1,0)) -->

<!-- write.csv(troyerex_compare, file = "files/troyerex_compare.csv", row.names = FALSE) -->
<!-- ``` -->
